### ISSUE TITLE
Smart Rollups: where to add them?

### ISSUE THREAD

**Issue by LaBoulange** [TheTezosCommunity/awesome-tezos#11]
I was going to add Etherlink when I realized I don't know where to add it. Shall we create a new category or does it fit in any existing one, in your opinion?

**Comment by skullzarmy** [comment]
Perhaps a 'Layer 2' category would be prudent? I'm not sure if that is technically correct.

**Comment by LaBoulange** [comment]
I think it sounds good. And we can change it later if we find a better idea!
