### ISSUE TITLE
Tezos Art Vending Machine: isn't it a marketplace rather than a tool?

### ISSUE THREAD

**Issue by LaBoulange** [TheTezosCommunity/awesome-tezos#4]
Just a suggestion: 

[Tezos Art Vending Machine](https://www.vendingnfts.xyz/) is currently listed as a NFT tool.
Isn't it more a marketplace? Users can buy NFTs there, and can donate works to the machine to get more visibility and hopefully secondary.

**Comment by skullzarmy** [comment]
Good catch! You're absolutely correct. I placed it in the wrong section.

**Comment by skullzarmy** [comment]
https://github.com/TheTezosCommunity/awesome-tezos/commit/e3155d61a144f09356cd6e00cd384c4a983fb213
