### ISSUE TITLE
Tools as a section or Tools subsections

### ISSUE THREAD

**Issue by skullzarmy** [TheTezosCommunity/awesome-tezos#7]
Should we categorize with a main Tools section then subcategories for focus, such as;
### DAO
[Homebase](...)

OR - have a Tools subcategory under the category for which it is focused, such as;

### DAO Tools
[Homebase](...)

**Comment by LaBoulange** [comment]
I was thinking of tools sections too, this morning.

I think it's best to have main categories for use cases (DAO, gaming, baking, etc) and subcategories for nature of links (apps, docs, tools, etc). The rationales behind that are that if we have a global tool section with subcategories, users will have difficulties to make the link between these subcategories and the corresponding functionals (DAO docs are there but DAO tools are there, gaming apps are there but game dev tools are there, and so on).

**Comment by skullzarmy** [comment]
Yes, I agree with you. Better to keep tools near their parent category for ease of browsing.

**Comment by LaBoulange** [comment]
That makes me think "Documentation" is a complicated one too: if you take OpenTezos for example, it contains pages related to the protocol, others to development and others related to baking. 
We could use documentation subcategories the same way as we have "tools", but this would lead us to duplicate links, which is something we don't want according to contributing.md.
I don't have a solution at the moment, just raising the point.

**Comment by skullzarmy** [comment]
How do you feel about linking in-doc to the documentation section when prudent?

**Comment by LaBoulange** [comment]
I didn't know we could do that! Let's go for it, that's a good idea!

**Comment by skullzarmy** [comment]
I'm talking the same idea as the top link or the section links in the contents. Just adding a 'Docs' link, in situ, wherever prudent.
